### ISSUE TITLE
A request for loosing the constraint of commonmark to solve the dependency conflict issues

### ISSUE THREAD

**Issue by NeolithEra** [GovReady/CommonMark-py-Extensions#4]
Hi, @JoshData **_commonmarkextensions_** set  a tight version constraint for package **_commonmark_**, which lead to a dependency conflict [#issue 3](https://github.com/govtrack/django-html-emailer/issues/3) in **_django-html-emailer_**.

I have checked **_commonmark 0.9.1_**, and confirmed that both **_django-html-emailer_** and **_Commonmarkextensions_** can work with **_commonmark 0.9.1_**. 
Maybe upgrading commonmark  to be >=0.8.0,<=0.9.1 is a good solution ^_^.

Thank you for your attention. 
I can submit a PR to fix this issue.

Best,
Neolith

**Comment by JoshData** [comment]
That sounds fine to me. @gregelin, are you OK with that change? This would allow using the latest upstream commonmark package which, I think, makes some minor updates to CommonMark parsing.

**Comment by hughdavenport** [comment]
I've added a new PR which fixes a compatibility issue which allows this library to work with commonmark 0.9.1.
Also, the old commonmark 0.8.1 doesn't work with python3.9 do to the deprecation of the unescape method (see https://github.com/readthedocs/commonmark.py/commit/e2f389456b39aece2d9ced16f3a3656caeb0a423), which in turn means this library also doesn't with it's current dependency restraints.

**Comment by lfalvarez** [comment]
hey! I was trying to use the gorgeous [django-html-emailer](govtrack/django-html-emailer) but apparently I chose the wrong version of python (3.9). Do we know if #8 is going to be merged?

**Comment by gregelin** [comment]
@JoshData I am fine with the change, if you have reviewed the code and it looks good.

**Comment by JoshData** [comment]
Merged, thanks!
